export const ADD_INGREDIENT:'ADD_INGREDIENT' = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT:'DELETE_INGREDIENT' = 'DELETE_INGREDIENT';
export const SORT_INGERDIENTS:'SORT_INGERDIENTS' = 'SORT_INGERDIENTS';
export const DELETE_BUN:'DELETE_BUN' = 'DELETE_BUN';
export const CLEAR_CONSTRUCTOR:'CLEAR_CONSTRUCTOR' = 'CLEAR_CONSTRUCTOR';